### ISSUE TITLE
Possible error in your altitude calcuation

### ISSUE THREAD

**Issue by bradcar** [jornamon/mp-bmp3xx-full#1]
In your code you have
    def altitude_from_pressure(self, press):
        return 44307.69 * (1 - (press / self._sea_level_pressure) ** 0.190284)

In the Bosch Sensor guide (ex: in bmp180 they show a different formula page 16 of: https://cdn-shop.adafruit.com/datasheets/BST-BMP180-DS000-09.pdf). Consider this return value instead:

        return 44330.0 * (1.0 - ((self.pressure / self.sea_level_pressure) ** (1.0 / 5.255)))

Notice that (1.0 / 5.255) = 0.1902949572, and not 0.190284, it is closer to 0.190295.

**Comment by jornamon** [comment]
Oh! Thank you for pointing this out—I probably typed it wrong and never looked back!

I took the opportunity to double-check the formulas, and I’ve updated the return value to:

`return 44330.77 * (1 - (press / self._sea_level_pressure) ** 0.190263)`

This should be the most accurate representation we can store in a float32, based on the constants derived from [this Wikipedia article](https://en.wikipedia.org/wiki/Barometric_formula).

Thank you again for bringing this to my attention, and I hope this resolves the issue!

**Comment by bradcar** [comment]
yes feel free to resolve.  Just so you know Bosch uses a different formula.  THANKS!

**Comment by bradcar** [comment]
Thanks!  I then found this at NCAR:  https://ncar.github.io/aircraft_ProcessingAlgorithms/www/PressureAltitude.pdf

**Comment by jornamon** [comment]
Thanks for sharing this document—it's very helpful! The Wikipedia article I linked to is less clear about the actual values of the constants, whereas this document is much more straightforward.
